### ISSUE TITLE
Please provide a LICENSE

### ISSUE THREAD

**Issue by yyyc514** [pocket-arduino/pocket_fighter#1]

**Comment by paladin-t** [comment]
Hi,

The license for the precompiled .HEX, and the .ARDUBOY package is [(CC) BY-SA](https://creativecommons.org/licenses/by-sa/4.0/).
However there is a [priced license](https://pocket-arduino.github.io/pocket_fighter/pocket_fighter/) for the source code.

Sincerely,
WRX.

**Comment by yyyc514** [comment]
It's typical to add a LICENSE file to your repository to make it easy to find.
